export const VEHICLE_SIZE_GUIDE = [
  {
    size: "Small",
    cardClass: "size-guide-card size-guide-card--small",
    description: "sedans, 2-rows, small trucks",
    vehicles: [
      "Accord",
      "Altima",
      "Bronco Sport",
      "Camry",
      "Corolla",
      "Crosstrek",
      "CX-30",
      "CX-5",
      "CX-50",
      "Elantra",
      "Equinox",
      "Escape",
      "Forester",
      "Forte",
      "GLC",
      "HR-V",
      "Integra",
      "Jetta",
      "Kicks",
      "Kona",
      "Maverick",
      "Model 3",
      "Prius",
      "RAV4",
      "Rogue",
      "Sentra",
      "Sportage",
      "Tiguan",
      "Trax",
      "Tucson"
    ]
  },
  {
    size: "Mid-Sized",
    cardClass: "size-guide-card size-guide-card--mid",
    description: "small 3rd rows, larger trucks",
    vehicles: [
      "Acadia",
      "Atlas",
      "Blazer",
      "Bronco",
      "CX-90",
      "Durango",
      "Explorer",
      "Frontier",
      "F Series",
      "Grand Cherokee",
      "Grand Highlander",
      "Model Y",
      "Murano",
      "Outback",
      "Palisade",
      "Passport",
      "Pilot",
      "Ranger",
      "RX",
      "Santa Fe",
      "Sierra",
      "Silverado",
      "Tacoma",
      "Tundra",
      "Telluride",
      "Traverse",
      "Wrangler"
    ]
  },
  {
    size: "Large",
    cardClass: "size-guide-card size-guide-card--large",
    description: "full-sized SUVs, minivans",
    vehicles: [
      "Armada",
      "Carnival",
      "Escalade",
      "Expedition",
      "Grand Wagoneer",
      "Navigator",
      "Odyssey",
      "Pacifica",
      "Sequoia",
      "Sienna",
      "Suburban",
      "Tahoe",
      "Wagoneer",
      "Yukon"
    ]
  }
] as const;
